server:
  port: 8088


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/r_mall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  dubbo:
    application:
      name: r-mall
    registry:
      address: zookeeper://127.0.0.1
      port: 2181
    scan: com.robot.home.controller
    consumer:
      check: false