server:
  port: 8078

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/r_mall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-idle: 6
        max-active: 32
        max-wait: 100
        min-idle: 4
  dubbo:
    application:
      name: r-mall #应用名
    registry:
      address: zookeeper://127.0.0.1 #zookeeper地址
      port: 2181 #提供注册的端口
    protocol:
      name: dubbo
      port: 20880 #dubbo服务暴露的端口
    scan: com.robot.product.provider #扫描的包名


mybatis:
  mapper-locations: classpath:mapper/*.xml
